'use client';

import { useState } from 'react';

export default function PrivacyPolicy() {
  const [lang, setLang] = useState('en');

  const content = {
    en: {
      title: 'Privacy Policy',
      intro: 'We hereby inform you about the processing of your personal data when using our website.',
      sec1Title: '1. Data Controller',
      sec1Text: 'Alexandru-Mihai Glontaru\nWilhelm-Caspar-Wegely-Platz 5\n10623 Berlin\nGermany\nEmail: aglontaru@sapiema.com',
      sec2Title: '2. Collection and storage of personal data as well as type and purpose of use',
      sec2Intro: 'When you visit our website, the browser used on your device automatically sends information to the server of our website. This information is temporarily stored in a so-called log file. The following information is recorded without your intervention and stored until automated deletion:',
      sec2List: [
        'IP address of the requesting computer,',
        'Date and time of access,',
        'Name and URL of the retrieved file,',
        'Website from which access is made (referrer URL),',
        'the browser used and, if applicable, the operating system of your computer as well as the name of your access provider.'
      ],
      sec2Mid: 'The aforementioned data will be processed by us for the following purposes:',
      sec2List2: [
        'Ensuring a smooth connection of the website,',
        'Ensuring comfortable use of our website,',
        'Evaluation of system security and stability as well as',
        'for further administrative purposes.'
      ],
      sec2End: 'The legal basis for data processing is Art. 6 (1) sentence 1 lit. f GDPR. Our legitimate interest follows from the data collection purposes listed above.',
      sec3Title: '3. Google Analytics',
      sec3P1: 'This website uses functions of the web analysis service Google Analytics. The provider is Google Ireland Limited ("Google"), Gordon House, Barrow Street, Dublin 4, Ireland.',
      sec3P2: 'Google Analytics uses so-called "cookies". These are text files that are stored on your computer and that allow an analysis of the use of the website by you. The information generated by the cookie about your use of this website is usually transmitted to a Google server in the USA and stored there.',
      sec3P3: 'The storage of Google Analytics cookies and the use of this analysis tool are based on Art. 6 (1) lit. a GDPR, provided you have given your consent via our cookie banner.',
      sec3IpTitle: 'IP Anonymization',
      sec3IpText: 'We have activated the IP anonymization function on this website. As a result, your IP address will be truncated by Google within member states of the European Union or in other contracting states of the Agreement on the European Economic Area before transmission to the USA.',
      sec4Title: '4. Rights of the Data Subject',
      sec4Intro: 'You have the right:',
      sec4List: [
        'pursuant to Art. 15 GDPR to request information about your personal data processed by us.',
        'pursuant to Art. 16 GDPR to immediately demand the correction of incorrect or completion of your personal data stored by us;',
        'pursuant to Art. 17 GDPR to request the deletion of your personal data stored by us;',
        'pursuant to Art. 18 GDPR to demand the restriction of the processing of your personal data;',
        'pursuant to Art. 20 GDPR to receive your personal data that you have provided to us in a structured, common, and machine-readable format;',
        'pursuant to Art. 7 (3) GDPR to revoke your once given consent to us at any time.'
      ]
    },
    de: {
      title: 'Datenschutzerklärung',
      intro: 'Wir informieren Sie hiermit über die Verarbeitung Ihrer personenbezogenen Daten bei der Nutzung unserer Website.',
      sec1Title: '1. Verantwortlicher',
      sec1Text: 'Alexandru-Mihai Glontaru\nWilhelm-Caspar-Wegely-Platz 5\n10623 Berlin\nGermany\nE-Mail: aglontaru@sapiema.com',
      sec2Title: '2. Erhebung und Speicherung personenbezogener Daten sowie Art und Zweck und deren Verwendung',
      sec2Intro: 'Beim Aufrufen unserer Website werden durch den auf Ihrem Endgerät zum Einsatz kommenden Browser automatisch Informationen an den Server unserer Website gesendet. Diese Informationen werden temporär in einem sog. Logfile gespeichert. Folgende Informationen werden dabei ohne Ihr Zutun erfasst und bis zur automatisierten Löschung gespeichert:',
      sec2List: [
        'IP-Adresse des anfragenden Rechners,',
        'Datum und Uhrzeit des Zugriffs,',
        'Name und URL der abgerufenen Datei,',
        'Website, von der aus der Zugriff erfolgt (Referrer-URL),',
        'verwendeter Browser und ggf. das Betriebssystem Ihres Rechners sowie der Name Ihres Access-Providers.'
      ],
      sec2Mid: 'Die genannten Daten werden durch uns zu folgenden Zwecken verarbeitet:',
      sec2List2: [
        'Gewährleistung eines reibungslosen Verbindungsaufbaus der Website,',
        'Gewährleistung einer komfortablen Nutzung unserer Website,',
        'Auswertung der Systemsicherheit und -stabilität sowie',
        'zu weiteren administrativen Zwecken.'
      ],
      sec2End: 'Die Rechtsgrundlage für die Datenverarbeitung ist Art. 6 Abs. 1 S. 1 lit. f DSGVO. Unser berechtigtes Interesse folgt aus oben aufgelisteten Zwecken zur Datenerhebung.',
      sec3Title: '3. Google Analytics',
      sec3P1: 'Diese Website nutzt Funktionen des Webanalysedienstes Google Analytics. Anbieter ist die Google Ireland Limited ("Google"), Gordon House, Barrow Street, Dublin 4, Irland.',
      sec3P2: 'Google Analytics verwendet so genannte "Cookies". Das sind Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.',
      sec3P3: 'Die Speicherung von Google-Analytics-Cookies und die Nutzung dieses Analyse-Tools erfolgen auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO, sofern Sie Ihre Einwilligung über unseren Cookie-Banner erteilt haben.',
      sec3IpTitle: 'IP Anonymisierung',
      sec3IpText: 'Wir haben auf dieser Website die Funktion IP-Anonymisierung aktiviert. Dadurch wird Ihre IP-Adresse von Google innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum vor der Übermittlung in die USA gekürzt.',
      sec4Title: '4. Betroffenenrechte',
      sec4Intro: 'Sie haben das Recht:',
      sec4List: [
        'gemäß Art. 15 DSGVO Auskunft über Ihre von uns verarbeiteten personenbezogenen Daten zu verlangen.',
        'gemäß Art. 16 DSGVO unverzüglich die Berichtigung unrichtiger oder Vervollständigung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;',
        'gemäß Art. 17 DSGVO die Löschung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;',
        'gemäß Art. 18 DSGVO die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen;',
        'gemäß Art. 20 DSGVO Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesebaren Format zu erhalten;',
        'gemäß Art. 7 Abs. 3 DSGVO Ihre einmal erteilte Einwilligung jederzeit gegenüber uns zu widerrufen.'
      ]
    }
  };

  const t = content[lang];

  return (
    <>
      <title>{`${t.title} | Alexandru Glontaru`}</title>
      <main style={{ padding: '120px 20px', maxWidth: '800px', margin: '0 auto', color: '#d4e4fa', lineHeight: '1.6' }}>
        
        <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '40px', gap: '10px' }}>
          <button 
            onClick={() => setLang('en')} 
            className={lang === 'en' ? 'btn-primary' : 'btn-outline'} 
            style={{ padding: '6px 14px', fontSize: '12px' }}
          >
            EN
          </button>
          <button 
            onClick={() => setLang('de')} 
            className={lang === 'de' ? 'btn-primary' : 'btn-outline'} 
            style={{ padding: '6px 14px', fontSize: '12px' }}
          >
            DE
          </button>
        </div>

        <h1 style={{ fontSize: '32px', color: '#f66a2e', marginBottom: '20px' }}>{t.title}</h1>
        <p>{t.intro}</p>

        <h2 style={{ fontSize: '20px', color: '#f66a2e', marginTop: '30px', marginBottom: '10px' }}>{t.sec1Title}</h2>
        <p style={{ whiteSpace: 'pre-wrap' }}>{t.sec1Text}</p>

        <h2 style={{ fontSize: '20px', color: '#f66a2e', marginTop: '30px', marginBottom: '10px' }}>{t.sec2Title}</h2>
        <p>{t.sec2Intro}</p>
        <ul style={{ marginLeft: '20px', marginBottom: '10px', listStyleType: 'disc' }}>
          {t.sec2List.map((item, idx) => <li key={idx}>{item}</li>)}
        </ul>
        <p>{t.sec2Mid}</p>
        <ul style={{ marginLeft: '20px', marginBottom: '10px', listStyleType: 'disc' }}>
          {t.sec2List2.map((item, idx) => <li key={idx}>{item}</li>)}
        </ul>
        <p>{t.sec2End}</p>

        <h2 style={{ fontSize: '20px', color: '#f66a2e', marginTop: '30px', marginBottom: '10px' }}>{t.sec3Title}</h2>
        <p>{t.sec3P1}</p>
        <p>{t.sec3P2}</p>
        <p>{t.sec3P3}</p>
        <p><strong>{t.sec3IpTitle}</strong><br />{t.sec3IpText}</p>

        <h2 style={{ fontSize: '20px', color: '#f66a2e', marginTop: '30px', marginBottom: '10px' }}>{t.sec4Title}</h2>
        <p>{t.sec4Intro}</p>
        <ul style={{ marginLeft: '20px', marginBottom: '10px', listStyleType: 'disc' }}>
          {t.sec4List.map((item, idx) => <li key={idx}>{item}</li>)}
        </ul>
      </main>
    </>
  );
}
